"use client";

import { FormEvent, useMemo, useState } from "react";

function localDate(daysAhead = 1) { const date = new Date(Date.now() + daysAhead * 86400000); date.setMinutes(date.getMinutes() - date.getTimezoneOffset()); return date.toISOString().slice(0, 10); }

export default function RentalOfferForm({ applicationId, defaultRent, defaultMoveIn, onCreated }: { applicationId: number; defaultRent: number; defaultMoveIn: string; onCreated: () => void }) {
  const minimum = useMemo(() => localDate(), []); const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(""); const form = new FormData(event.currentTarget); try { const response = await fetch("/api/rental-offers", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ applicationId, monthlyRent: Number(form.get("monthlyRent")), deposit: Number(form.get("deposit")), moveInDate: form.get("moveInDate"), leaseMonths: Number(form.get("leaseMonths")), terms: form.get("terms") }) }); const text = await response.text(); const data = text ? JSON.parse(text) as { error?: string } : {}; if (!response.ok) throw new Error(data.error || "Unable to send the offer."); onCreated(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to send the offer."); } finally { setSaving(false); } }
  if (!open) return <button className="offer-open" onClick={() => setOpen(true)}>Create rental offer</button>;
  return <form className="offer-form" onSubmit={submit}><div><strong>Rental offer</strong><button type="button" aria-label="Close rental offer form" onClick={() => setOpen(false)}>×</button></div><label><span>Monthly rent (ETB)</span><input name="monthlyRent" type="number" min="1" max="100000000" defaultValue={defaultRent} required /></label><label><span>Deposit (ETB)</span><input name="deposit" type="number" min="0" max="200000000" defaultValue="0" required /></label><label><span>Move-in date</span><input name="moveInDate" type="date" min={minimum} defaultValue={defaultMoveIn >= minimum ? defaultMoveIn : minimum} required /></label><label><span>Lease length</span><select name="leaseMonths" defaultValue="12"><option value="1">1 month</option><option value="3">3 months</option><option value="6">6 months</option><option value="12">12 months</option><option value="24">24 months</option></select></label><label><span>Important terms</span><textarea name="terms" rows={3} maxLength={1500} placeholder="Utilities, payment date, house rules, or other agreed details…" /></label>{error && <small className="form-error">{error}</small>}<button className="accept" disabled={saving}>{saving ? "Sending…" : "Send offer"}</button></form>;
}
