import type { Metadata } from "next";
import Link from "next/link";
import { env } from "cloudflare:workers";
import FavoriteButton from "@/app/components/favorite-button";
import { getChatGPTUser } from "@/app/chatgpt-auth";

export const dynamic = "force-dynamic";
type ListingDetail = { id:number; title:string; description:string; monthlyRent:number; deposit:number; roomType:string; bedrooms:number; bathrooms:number; furnished:number; utilitiesIncluded:number; availableFrom:string; houseRules:string; verificationStatus:string; city:string; neighborhood:string|null; ownerName:string|null };
const labels:Record<string,string>={private_room:"Private room",shared_room:"Shared room",apartment:"Apartment",house:"House"};

async function getListing(id:number) {
  return await env.DB.prepare(`SELECT l.id,l.title,l.description,l.monthly_rent AS monthlyRent,l.deposit,l.room_type AS roomType,l.bedrooms,l.bathrooms,l.furnished,l.utilities_included AS utilitiesIncluded,l.available_from AS availableFrom,l.house_rules AS houseRules,l.verification_status AS verificationStatus,city.name AS city,neighborhood.name AS neighborhood,p.first_name AS ownerName FROM listings l JOIN locations city ON city.id=l.city_id LEFT JOIN locations neighborhood ON neighborhood.id=l.neighborhood_id LEFT JOIN profiles p ON p.user_id=l.owner_id WHERE l.id=? AND l.status='active'`).bind(id).first<ListingDetail>();
}
export async function generateMetadata({params}:{params:Promise<{id:string}>}):Promise<Metadata>{const {id}=await params;const item=await getListing(Number(id));if(!item)return{title:"Listing not found | Debal",openGraph:{images:[]},twitter:{images:[]}};return{title:`${item.title} | Debal`,description:item.description.slice(0,155),openGraph:{title:item.title,description:item.description.slice(0,155),images:[]},twitter:{card:"summary",title:item.title,description:item.description.slice(0,155),images:[]}};}
export default async function ListingDetailPage({params}:{params:Promise<{id:string}>}){const {id}=await params;const item=await getListing(Number(id));if(!item)return <main className="detail-missing"><h1>Listing not found</h1><Link className="button button-dark" href="/listings">Browse available homes</Link></main>;const identity=await getChatGPTUser();let saved=false;if(identity){const row=await env.DB.prepare("SELECT id FROM favorites WHERE user_id=? AND listing_id=?").bind(identity.userId,item.id).first();saved=Boolean(row);}let rules:string[]=[];try{rules=JSON.parse(item.houseRules||"[]");}catch{}
return <main className="detail-page"><header className="site-header shell market-header"><Link className="brand" href="/" aria-label="Debal home"><span className="brand-logo" aria-hidden="true" /></Link><nav><Link href="/listings">Browse homes</Link><Link href="/favorites">Saved listings</Link></nav><Link className="button button-dark" href="/listings/new">List a place</Link></header><section className="detail-visual shell"><Link href="/listings" className="back-link">← All listings</Link><div className="detail-photo"><span>{item.verificationStatus==="verified"?"✓ Verified property":"Property verification pending"}</span><b>DEBAL HOME</b></div></section><section className="detail-layout shell"><article><span className="area">{item.neighborhood?`${item.neighborhood}, `:""}{item.city}</span><h1>{item.title}</h1><p className="detail-description">{item.description}</p><div className="detail-specs"><div><small>Property type</small><strong>{labels[item.roomType]}</strong></div><div><small>Bedrooms</small><strong>{item.bedrooms}</strong></div><div><small>Bathrooms</small><strong>{item.bathrooms}</strong></div><div><small>Furnishing</small><strong>{item.furnished?"Furnished":"Unfurnished"}</strong></div><div><small>Utilities</small><strong>{item.utilitiesIncluded?"Included":"Separate"}</strong></div><div><small>Available</small><strong>{item.availableFrom}</strong></div></div>{rules.length>0&&<div className="house-rules"><h2>House rules</h2><ul>{rules.map((rule)=><li key={rule}>{rule}</li>)}</ul></div>}<aside className="safety-note"><strong>Safety first:</strong> View the property and verify the person before paying or sharing sensitive documents.</aside></article><aside className="detail-booking"><span>Monthly rent</span><strong>{Number(item.monthlyRent).toLocaleString()} ETB<small>/month</small></strong><p>Deposit: {Number(item.deposit).toLocaleString()} ETB</p><div className="owner-line"><span>{item.ownerName?.slice(0,1)||"D"}</span><div><small>Listed by</small><strong>{item.ownerName||"Debal member"}</strong></div></div><FavoriteButton listingId={item.id} initialSaved={saved}/><button className="button button-dark" type="button">Request a conversation <span>→</span></button><small>Phone numbers stay private until both people choose to share.</small></aside></section></main>}
