"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

type Report = { id: number; targetType: string; listingId: number | null; reportedUserId: string | null; reason: string; details: string; status: string; moderatorNote: string; createdAt: string; listingTitle: string | null; reportedName: string | null; reporterName: string | null };

export default function ModerationPage() {
  const [items, setItems] = useState<Report[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [notes, setNotes] = useState<Record<number, string>>({});
  async function load() { setLoading(true); try { const response = await fetch("/api/moderation/reports"); const text = await response.text(); const data = text ? JSON.parse(text) as { reports?: Report[]; error?: string } : {}; if (!response.ok) throw new Error(data.error || "Unable to load reports."); setItems(data.reports ?? []); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to load reports."); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  async function update(id: number, status: string) { setError(""); const response = await fetch("/api/moderation/reports", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id, status, note: notes[id] || "" }) }); const text = await response.text(); const data = text ? JSON.parse(text) as { error?: string } : {}; if (!response.ok) { setError(data.error || "Unable to update report."); return; } setItems((current) => current.map((item) => item.id === id ? { ...item, status, moderatorNote: notes[id] || "" } : item)); }
  return <main className="moderation-page"><header className="site-header shell market-header"><Link className="brand" href="/"><span className="brand-logo" /></Link><nav><Link href="/listings">Marketplace</Link><Link href="/dashboard">Dashboard</Link></nav><Link className="button button-dark" href="/">Debal home</Link></header><section className="moderation-shell shell"><span className="eyebrow">TRUST & SAFETY</span><h1>Review community reports.</h1><p>Use the evidence provided, check the related profile or listing, and record a clear outcome.</p>{error && <p className="form-error dashboard-error">{error}</p>}{loading ? <p>Loading reports…</p> : items.length === 0 ? <div className="empty-state"><strong>No reports to review.</strong></div> : <div className="report-list">{items.map((item) => <article className="report-card" key={item.id}><div className="report-copy"><div><span className={`status-pill ${item.status}`}>{item.status}</span><span>{item.targetType} · {item.reason}</span></div><h2>{item.listingTitle || item.reportedName || "Reported member"}</h2><p>{item.details || "No additional details were supplied."}</p><small>Reported by {item.reporterName || "Debal member"} · {new Date(item.createdAt).toLocaleString()}</small>{item.listingId && <Link href={`/listings/${item.listingId}`}>Open listing →</Link>}{item.reportedUserId && <Link href={`/roommates/${item.reportedUserId}`}>Open member profile →</Link>}</div><div className="report-review"><textarea rows={3} placeholder="Moderator note" value={notes[item.id] ?? item.moderatorNote} onChange={(event) => setNotes((current) => ({ ...current, [item.id]: event.target.value }))} /><div><button onClick={() => void update(item.id, "reviewing")}>Reviewing</button><button className="resolve" onClick={() => void update(item.id, "resolved")}>Resolve</button><button onClick={() => void update(item.id, "dismissed")}>Dismiss</button></div></div></article>)}</div>}</section></main>;
}
